### PR TITLE
Fixed bugs and implemented Material icons, progress bar group

### PR DESCRIPTION
**Pull request by tom-beardedhen**
Fixed issues: #164 #162 #161 #155 #119 
Added Material Icon font #166
Added progress bar group to allow for stacked progress bars, and added progress % label see #165

### CODE REVIEW

**Comment by beylerian** [comment]
hello, would really appreciate the update if no issues, thanks!

**Comment by jamie-beardedhen** [comment]
I'll merge this and publish to Maven Central when I get a spare moment

**Comment by Gohan** [comment]
Hi, I want to test this pull request, I merged @tom-beardedhen's master branch, there are some errors of javadoc generate

https://jitpack.io/com/github/bzs/Android-Bootstrap/d7cd2389/build.log

**Comment by tom-beardedhen** [comment]
Hi @Gohan I will take a look in the that when I get a chance as the jetpack log is not very useful. 
Tom

**Comment by tom-beardedhen** [comment]
@Gohan I have generated java docs through android Studio successfully,  do you have nay idea what causes this and dose it stop you using it?

**Comment by Gohan** [comment]
@tom-beardedhen  I am not sure, I just fork the Bearded-Hen/Android-Bootstrap repo, use the master branch, then merge your master branch, then publish the tag for jitpack usage.

**Comment by jamie-beardedhen** [comment]
@tom-beardedhen the Javadoc method link needs qualification in ProgressView, which will throw off the build process. See http://stackoverflow.com/questions/5915992

The support annotation warnings have always been there, I guess we should open up another issue for those.

**Pull request merged**
